kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-coodinator-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-coodinator
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Release.Name }}-coodinator
  apiGroup: ""